resource "ndfc_interface_vlan" "example" {
  serial_number                = "9DBYO6WQJ46"
  interface_name               = "vlan1234"
  policy                       = "int_vlan"
  vrf                          = "default"
  ipv4_address                 = "5.6.7.8"
  ipv4_prefix_length           = 24
  mtu                          = 9216
  routing_tag                  = "12346"
  disable_ip_redirects         = false
  interface_description        = "My interface description"
  freeform_config              = "delay 200"
  admin_state                  = false
  hsrp                         = false
  hsrp_vip                     = "5.6.7.1"
  hsrp_group                   = 1
  hsrp_version                 = "1"
  hsrp_priority                = 100
  hsrp_preempt                 = true
  hsrp_mac                     = "0000.0C07.AC01"
  dhcp_server_1                = "10.10.10.1"
  dhcp_server_1_vrf            = "VRF1"
  dhcp_server_2                = "10.10.10.2"
  dhcp_server_2_vrf            = "VRF1"
  dhcp_server_3                = "10.10.10.3"
  dhcp_server_3_vrf            = "VRF1"
  advertise_subnet_in_underlay = true
  netflow                      = false
}
