// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAccDataSource
func TestAccDataSourceNdfcInterfaceLoopback(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNdfcInterfaceLoopbackConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "serial_number", "9DBYO6WQJ46"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "interface_name", "loopback123"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "policy", "int_loopback"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "vrf", "VRF1"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "ipv4_address", "5.6.7.8"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "ipv6_address", "2001::10"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "route_map_tag", "12346"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "interface_description", "My interface description"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "freeform_config", "logging event port link-status"),
					resource.TestCheckResourceAttr("data.ndfc_interface_loopback.test", "admin_state", "false"),
				),
			},
		},
	})
}

//template:end testAccDataSource

//template:begin testAccDataSourceConfig
const testAccDataSourceNdfcInterfaceLoopbackConfig = `

resource "ndfc_interface_loopback" "test" {
	serial_number = "9DBYO6WQJ46"
	interface_name = "loopback123"
	policy = "int_loopback"
	vrf = "VRF1"
	ipv4_address = "5.6.7.8"
	ipv6_address = "2001::10"
	route_map_tag = "12346"
	interface_description = "My interface description"
	freeform_config = "logging event port link-status"
	admin_state = false
}

data "ndfc_interface_loopback" "test" {
	serial_number = "9DBYO6WQJ46"
	interface_name = "loopback123"

	depends_on = [ndfc_interface_loopback.test]
}
`

//template:end testAccDataSourceConfig
