// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-nd"
)

//template:end imports

//template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &InterfaceLoopbackDataSource{}
	_ datasource.DataSourceWithConfigure = &InterfaceLoopbackDataSource{}
)

func NewInterfaceLoopbackDataSource() datasource.DataSource {
	return &InterfaceLoopbackDataSource{}
}

type InterfaceLoopbackDataSource struct {
	client *nd.Client
}

func (d *InterfaceLoopbackDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_loopback"
}

func (d *InterfaceLoopbackDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read a Interface Loopback.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The id of the object",
				Computed:            true,
			},
			"serial_number": schema.StringAttribute{
				MarkdownDescription: "Serial number of switch to configure",
				Required:            true,
			},
			"interface_name": schema.StringAttribute{
				MarkdownDescription: "Name of the Interface. Example: `loopback123`",
				Required:            true,
			},
			"policy": schema.StringAttribute{
				MarkdownDescription: "Name of the policy. Examples: `int_loopback`, `int_multisite_loopback`, `int_freeform`",
				Computed:            true,
			},
			"vrf": schema.StringAttribute{
				MarkdownDescription: "Interface VRF name, default VRF if not specified",
				Computed:            true,
			},
			"ipv4_address": schema.StringAttribute{
				MarkdownDescription: "For VxLAN fabrics, configure an IPv4 address if underlay is V4 and VRF is default, otherwise add the config to freeform if underlay is V6.  For non-VxLAN fabrics or non-default VRF, loopback interfaces can have both IPv4 and IPv6 addresses.",
				Computed:            true,
			},
			"ipv6_address": schema.StringAttribute{
				MarkdownDescription: "For VxLAN fabrics, configure an IPv6 address if underlay is V6 and VRF is default, otherwise add the config to freeform if underlay is V4.  For non-VxLAN fabrics or non-default VRF, loopback interfaces can have both IPv4 and IPv6 addresses.",
				Computed:            true,
			},
			"route_map_tag": schema.StringAttribute{
				MarkdownDescription: "Route-Map tag associated with interface IP",
				Computed:            true,
			},
			"interface_description": schema.StringAttribute{
				MarkdownDescription: "Interface description",
				Computed:            true,
			},
			"freeform_config": schema.StringAttribute{
				MarkdownDescription: "Additional CLI for the interface",
				Computed:            true,
			},
			"admin_state": schema.BoolAttribute{
				MarkdownDescription: "Enable or disable the interface",
				Computed:            true,
			},
		},
	}
}

func (d *InterfaceLoopbackDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.client = req.ProviderData.(*NdfcProviderData).Client
}

//template:end model

func (d *InterfaceLoopbackDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config InterfaceLoopback

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.Id.String()))

	res, err := d.client.Get(fmt.Sprintf("%v?serialNumber=%v&ifName=%v", config.getPath(), config.SerialNumber.ValueString(), config.InterfaceName.ValueString()))
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
		return
	}

	config.fromBody(ctx, res)
	config.Id = types.StringValue(config.SerialNumber.ValueString() + "/" + config.InterfaceName.ValueString())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.Id.ValueString()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
