// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"
	"fmt"
	"strings"
	"sync"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-nd"
	"github.com/netascode/terraform-provider-ndfc/internal/provider/helpers"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin model

// Ensure provider defined types fully satisfy framework interfaces
var _ resource.Resource = &InterfaceVlanResource{}
var _ resource.ResourceWithImportState = &InterfaceVlanResource{}

func NewInterfaceVlanResource() resource.Resource {
	return &InterfaceVlanResource{}
}

type InterfaceVlanResource struct {
	client      *nd.Client
	updateMutex *sync.Mutex
}

func (r *InterfaceVlanResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_vlan"
}

func (r *InterfaceVlanResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: helpers.NewAttributeDescription("This resource can manage a Interface Vlan.").String,

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The id of the object",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"serial_number": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Serial number of switch to configure").String,
				Optional:            true,
			},
			"interface_name": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Name of the Interface. Example: `vlan1234`").String,
				Optional:            true,
			},
			"policy": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Name of the policy. Examples: `int_vlan`, `int_freeform`").AddDefaultValueDescription("int_vlan").String,
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("int_vlan"),
			},
			"vrf": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Interface VRF name, default VRF if not specified").String,
				Optional:            true,
			},
			"ipv4_address": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("For VxLAN fabrics, configure an IPv4 address if underlay is V4 and VRF is default, otherwise add the config to freeform if underlay is V6.  For non-VxLAN fabrics or non-default VRF, loopback interfaces can have both IPv4 and IPv6 addresses.").String,
				Optional:            true,
			},
			"ipv4_prefix_length": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("IP netmask length used with the IP address").AddIntegerRangeDescription(1, 31).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 31),
				},
			},
			"mtu": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("MTU for the interface").AddIntegerRangeDescription(68, 9216).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(68, 9216),
				},
			},
			"routing_tag": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Routing tag associated with interface IP").String,
				Optional:            true,
			},
			"disable_ip_redirects": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Disables both IPv4/IPv6 redirects on the interface").AddDefaultValueDescription("true").String,
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
			},
			"interface_description": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Interface description").String,
				Optional:            true,
			},
			"freeform_config": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Additional CLI for the interface").String,
				Optional:            true,
			},
			"admin_state": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable or disable the interface").AddDefaultValueDescription("true").String,
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
			},
			"hsrp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable HSRP Flag").String,
				Optional:            true,
			},
			"hsrp_vip": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("HSRP IPv4 Address. HSRP VIP must be same on active/standby device").String,
				Optional:            true,
			},
			"hsrp_group": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("HSRP group number").String,
				Optional:            true,
			},
			"hsrp_version": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("HSRP version").AddStringEnumDescription("1", "2").AddDefaultValueDescription("1").String,
				Optional:            true,
				Computed:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("1", "2"),
				},
				Default: stringdefault.StaticString("1"),
			},
			"hsrp_priority": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("HSRP priority").AddIntegerRangeDescription(0, 255).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 255),
				},
			},
			"hsrp_preempt": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable Preempt. Overthrow lower priority Active routers").AddDefaultValueDescription("false").String,
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(false),
			},
			"hsrp_mac": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("HSRP Virtual MAC Address").String,
				Optional:            true,
			},
			"dhcp_server_1": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("DHCPv4 Server 1").String,
				Optional:            true,
			},
			"dhcp_server_1_vrf": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("DHCPv4 Server 1 VRF").String,
				Optional:            true,
			},
			"dhcp_server_2": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("DHCPv4 Server 2").String,
				Optional:            true,
			},
			"dhcp_server_2_vrf": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("DHCPv4 Server 2 VRF").String,
				Optional:            true,
			},
			"dhcp_server_3": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("DHCPv4 Server 3").String,
				Optional:            true,
			},
			"dhcp_server_3_vrf": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("DHCPv4 Server 3 VRF").String,
				Optional:            true,
			},
			"advertise_subnet_in_underlay": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Advertise Subnet into Underlay IGP").AddDefaultValueDescription("false").String,
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(false),
			},
			"netflow": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Netflow is supported only if it is enabled on fabric").AddDefaultValueDescription("false").String,
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(false),
			},
			"netflow_monitor": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Provide the Layer 3 Monitor Name").String,
				Optional:            true,
			},
			"netflow_sampler": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Netflow sampler name, applicable to N7K only").String,
				Optional:            true,
			},
		},
	}
}

func (r *InterfaceVlanResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.client = req.ProviderData.(*NdfcProviderData).Client
	r.updateMutex = req.ProviderData.(*NdfcProviderData).UpdateMutex
}

//template:end model

func (r *InterfaceVlanResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan InterfaceVlan

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.Id.ValueString()))

	// Create object
	body := plan.toBody(ctx)

	res, err := r.client.Post(plan.getPath(), body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to configure object (PUT), got error: %s, %s", err, res.String()))
		return
	}

	// Deploy interface
	r.updateMutex.Lock()
	defer r.updateMutex.Unlock()
	diags = helpers.DeployInterface(ctx, r.client, plan.SerialNumber.ValueString(), plan.InterfaceName.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Id = types.StringValue(plan.SerialNumber.ValueString() + "/" + plan.InterfaceName.ValueString())

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *InterfaceVlanResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state InterfaceVlan

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Id.String()))

	res, err := r.client.Get(fmt.Sprintf("%v?serialNumber=%v&ifName=%v", state.getPath(), state.SerialNumber.ValueString(), state.InterfaceName.ValueString()))
	if err != nil {
		if strings.Contains(err.Error(), "StatusCode 400") || strings.Contains(err.Error(), "StatusCode 500") {
			resp.State.RemoveResource(ctx)
			return
		} else {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (GET), got error: %s, %s", err, res.String()))
			return
		}
	}

	state.fromBody(ctx, res)

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Id.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *InterfaceVlanResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan InterfaceVlan

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Update", plan.Id.ValueString()))

	body := plan.toBody(ctx)
	res, err := r.client.Put(plan.getPath(), body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to configure object (PUT), got error: %s, %s", err, res.String()))
		return
	}

	// Deploy interface
	r.updateMutex.Lock()
	defer r.updateMutex.Unlock()
	diags = helpers.DeployInterface(ctx, r.client, plan.SerialNumber.ValueString(), plan.InterfaceName.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Update finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *InterfaceVlanResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state InterfaceVlan

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Id.ValueString()))

	body, _ := sjson.Set("", "0.serialNumber", state.SerialNumber.ValueString())
	body, _ = sjson.Set(body, "0.ifName", state.InterfaceName.ValueString())
	res, err := r.client.Delete(state.getPath(), body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete object (DELETE), got error: %s, %s", err, res.String()))
		return
	}

	// Deploy interface
	r.updateMutex.Lock()
	defer r.updateMutex.Unlock()
	diags = helpers.DeployInterface(ctx, r.client, state.SerialNumber.ValueString(), state.InterfaceName.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Id.ValueString()))

	resp.State.RemoveResource(ctx)
}

//template:begin import
func (r *InterfaceVlanResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
	idParts := strings.Split(req.ID, ":")

	if len(idParts) != 2 || idParts[0] == "" || idParts[1] == "" {
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("Expected import identifier with format: '<serial_number>:<interface_name>'. Got: %q", req.ID),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("serial_number"), idParts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("interface_name"), idParts[1])...)
}

//template:end import
