// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAcc
func TestAccNdfcInterfaceVlan(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccNdfcInterfaceVlanConfigMinimal,
			},
			{
				Config: testAccNdfcInterfaceVlanConfigAll,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "serial_number", "9DBYO6WQJ46"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "interface_name", "vlan1234"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "policy", "int_vlan"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "vrf", "default"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "ipv4_address", "5.6.7.8"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "ipv4_prefix_length", "24"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "mtu", "9216"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "routing_tag", "12346"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "disable_ip_redirects", "false"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "interface_description", "My interface description"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "freeform_config", "delay 200"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "admin_state", "false"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "hsrp", "false"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "hsrp_vip", "5.6.7.1"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "hsrp_group", "1"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "hsrp_version", "1"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "hsrp_priority", "100"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "hsrp_preempt", "true"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "hsrp_mac", "0000.0C07.AC01"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "dhcp_server_1", "10.10.10.1"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "dhcp_server_1_vrf", "VRF1"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "dhcp_server_2", "10.10.10.2"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "dhcp_server_2_vrf", "VRF1"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "dhcp_server_3", "10.10.10.3"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "dhcp_server_3_vrf", "VRF1"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "advertise_subnet_in_underlay", "true"),
					resource.TestCheckResourceAttr("ndfc_interface_vlan.test", "netflow", "false"),
				),
			},
			{
				ResourceName:  "ndfc_interface_vlan.test",
				ImportState:   true,
				ImportStateId: "9DBYO6WQJ46:vlan1234",
			},
		},
	})
}

//template:end testAcc

//template:begin testAccConfigMinimal
const testAccNdfcInterfaceVlanConfigMinimal = `

resource "ndfc_interface_vlan" "test" {
	serial_number = "9DBYO6WQJ46"
	interface_name = "vlan1234"
}
`

//template:end testAccConfigMinimal

//template:begin testAccConfigAll
const testAccNdfcInterfaceVlanConfigAll = `

resource "ndfc_interface_vlan" "test" {
	serial_number = "9DBYO6WQJ46"
	interface_name = "vlan1234"
	policy = "int_vlan"
	vrf = "default"
	ipv4_address = "5.6.7.8"
	ipv4_prefix_length = 24
	mtu = 9216
	routing_tag = "12346"
	disable_ip_redirects = false
	interface_description = "My interface description"
	freeform_config = "delay 200"
	admin_state = false
	hsrp = false
	hsrp_vip = "5.6.7.1"
	hsrp_group = 1
	hsrp_version = "1"
	hsrp_priority = 100
	hsrp_preempt = true
	hsrp_mac = "0000.0C07.AC01"
	dhcp_server_1 = "10.10.10.1"
	dhcp_server_1_vrf = "VRF1"
	dhcp_server_2 = "10.10.10.2"
	dhcp_server_2_vrf = "VRF1"
	dhcp_server_3 = "10.10.10.3"
	dhcp_server_3_vrf = "VRF1"
	advertise_subnet_in_underlay = true
	netflow = false
}
`

//template:end testAccConfigAll
